apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.kodein.di:kodein-di-generic-jvm:$kodein_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation "io.arrow-kt:arrow-core-data:$arrow_version"
}

sourceSets {
    main { java.srcDirs = ['src/main/kotlin'] }
    test { java.srcDirs = ['src/test/kotlin'] }
}

compileKotlin {
    kotlinOptions.jvmTarget = '1.8'
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"